# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       pebble

# >> macros
# << macros

%{!?qtc_qmake:%define qtc_qmake %qmake}
%{!?qtc_qmake5:%define qtc_qmake5 %qmake5}
%{!?qtc_make:%define qtc_make make}
%{?qtc_builddir:%define _builddir %qtc_builddir}
Summary:    Support for Pebble watch in SailfishOS
Version:    0.12
Release:    1
Group:      Qt/Qt
License:    GPL3
URL:        http://getpebble.com/
Source0:    %{name}-%{version}.tar.xz
Source100:  pebble.yaml
Requires:   sailfishsilica-qt5 >= 0.10.9
Requires:   systemd-user-session-targets
BuildRequires:  pkgconfig(Qt5DBus)
BuildRequires:  pkgconfig(Qt5Bluetooth)
BuildRequires:  pkgconfig(Qt5Contacts)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(mlite5)
BuildRequires:  pkgconfig(sailfishapp) >= 0.0.10
BuildRequires:  desktop-file-utils

%description
Support for Pebble watch to receive events from SailfishOS device via Bluetooth.


%package -n harbour-pebble
Summary:    Support for Pebble watch in SailfishOS
Group:      Qt/Qt

%description -n harbour-pebble
Support for Pebble watch to receive events from SailfishOS device via Bluetooth.


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qtc_qmake5  \
    VERSION='%{version}-%{release}'

%qtc_make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
mkdir -p %{buildroot}%{_libdir}/systemd/user/user-session.target.wants
ln -s ../pebbled.service %{buildroot}%{_libdir}/systemd/user/user-session.target.wants/

cp %{buildroot}%{_bindir}/%{name} %{buildroot}%{_bindir}/harbour-%{name}
cp -r %{buildroot}%{_datadir}/%{name}/qml %{buildroot}%{_datadir}/harbour-%{name}/
cp %{buildroot}%{_bindir}/%{name}d %{buildroot}%{_datadir}/harbour-%{name}/
mv %{buildroot}%{_datadir}/harbour-%{name}/harbour-pebble.desktop %{buildroot}%{_datadir}/applications/
mv %{buildroot}%{_datadir}/harbour-%{name}/harbour-pebble.png %{buildroot}%{_datadir}/icons/hicolor/86x86/apps/
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%post
# >> post
systemctl --user daemon-reload
# << post

%files
%defattr(-,root,root,-)
%{_bindir}/%{name}
%{_bindir}/%{name}d
%{_datadir}/%{name}/qml
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/hicolor/86x86/apps/%{name}.png
%{_libdir}/systemd/user/%{name}d.service
%{_libdir}/systemd/user/user-session.target.wants/%{name}d.service
%{_datadir}/%{name}/log4qt.conf
# >> files
# << files

%files -n harbour-pebble
%defattr(-,root,root,-)
%{_bindir}/harbour-%{name}
%{_datadir}/harbour-%{name}/%{name}d
%{_datadir}/harbour-%{name}/qml
%{_datadir}/applications/harbour-%{name}.desktop
%{_datadir}/icons/hicolor/86x86/apps/harbour-%{name}.png
# >> files harbour-pebble
# << files harbour-pebble
